
# Student Performance Prediction

## 1. Import Libraries

In [4]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

## 2. Load Dataset

In [5]:

df = pd.read_csv('Students Performance .csv')
df.head()

,Student_ID,Student_Age,Sex,High_School_Type,Scholarship,Additional_Work,Sports_activity,Transportation,Weekly_Study_Hours,Attendance,Reading,Notes,Listening_in_Class,Project_work,Grade
0,STUDENT1,19-22,Male,Other,50%,Yes,No,Private,0,Always,Yes,Yes,No,No,AA
1,STUDENT2,19-22,Male,Other,50%,Yes,No,Private,0,Always,Yes,No,Yes,Yes,AA
2,STUDENT3,19-22,Male,State,50%,No,No,Private,2,Never,No,No,No,Yes,AA
3,STUDENT4,18,Female,Private,50%,Yes,No,Bus,2,Always,No,Yes,No,No,AA
4,STUDENT5,19-22,Male,Private,50%,No,No,Bus,12,Always,Yes,No,Yes,Yes,AA

## 3. Data Exploration

In [6]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          145 non-null    object
 1   Student_Age         145 non-null    object
 2   Sex                 145 non-null    object
 3   High_School_Type    145 non-null    object
 4   Scholarship         144 non-null    object
 5   Additional_Work     145 non-null    object
 6   Sports_activity     145 non-null    object
 7   Transportation      145 non-null    object
 8   Weekly_Study_Hours  145 non-null    int64
 9   Attendance          145 non-null    object
 10  Reading             145 non-null    object
 11  Notes               145 non-null    object
 12  Listening_in_Class  145 non-null    object
 13  Project_work        145 non-null    object
 14  Grade               145 non-null    object
dtypes: int64(1), object(14)
memory usage: 17.1+ KB

In [7]:

df.describe()

       Weekly_Study_Hours
count          145.000000
mean             2.331034
std              4.249273
min              0.000000
25%              0.000000
50%              0.000000
75%              2.000000
max             12.000000

## 4. Data Preprocessing

In [8]:

# Remove ID column if present
if 'Student_ID' in df.columns:
    df = df.drop(columns=['Student_ID'])

# Encode categorical variables
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

df.head()

,Student_Age,Sex,High_School_Type,Scholarship,Additional_Work,Sports_activity,Transportation,Weekly_Study_Hours,Attendance,Reading,Notes,Listening_in_Class,Project_work,Grade
0,1,1,0,2,1,0,1,0,1,1,2,1,0,0
1,1,1,0,2,1,0,1,0,1,1,1,2,1,0
2,1,1,2,2,0,0,1,2,2,0,1,1,1,0
3,0,0,1,2,1,0,0,2,1,0,2,1,0,0
4,1,1,1,2,0,0,0,12,1,1,1,2,1,0

## 5. Define Features and Target

In [9]:

X = df.drop('Grade', axis=1)
y = df['Grade']

## 6. Train Test Split

In [10]:

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


# Model 1: Logistic Regression

In [11]:

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

In [12]:

print("Logistic Regression Metrics")

print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("Precision:", precision_score(y_test, y_pred_log, average='weighted'))
print("Recall:", recall_score(y_test, y_pred_log, average='weighted'))
print("F1 Score:", f1_score(y_test, y_pred_log, average='weighted'))

print("\nClassification Report")
print(classification_report(y_test, y_pred_log))

Logistic Regression Metrics
Accuracy: 0.2413793103448276
Precision: 0.46091954022988507
Recall: 0.2413793103448276
F1 Score: 0.2719211822660098

Classification Report
              precision    recall  f1-score   support

           0       0.07      0.33      0.11         3
           1       0.67      0.50      0.57         4
           2       1.00      0.33      0.50         6
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         4
           6       0.25      0.50      0.33         2
           7       1.00      0.25      0.40         4

    accuracy                           0.24        29
   macro avg       0.37      0.24      0.24        29
weighted avg       0.46      0.24      0.27        29

c:\Users\surya prasad mallik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\surya prasad mallik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\surya prasad mallik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\surya prasad mallik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


# Model 2: Decision Tree Classifier

In [13]:

dt_model = DecisionTreeClassifier()

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

In [14]:

print("Decision Tree Metrics")

print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt, average='weighted'))
print("Recall:", recall_score(y_test, y_pred_dt, average='weighted'))
print("F1 Score:", f1_score(y_test, y_pred_dt, average='weighted'))

print("\nClassification Report")
print(classification_report(y_test, y_pred_dt))

Decision Tree Metrics
Accuracy: 0.1724137931034483
Precision: 0.17701149425287355
Recall: 0.1724137931034483
F1 Score: 0.17350848385331144

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
           1       0.20      0.25      0.22         4
           2       0.33      0.33      0.33         6
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         3
           5       0.33      0.25      0.29         4
           6       0.50      0.50      0.50         2
           7       0.00      0.00      0.00         4

    accuracy                           0.17        29
   macro avg       0.17      0.17      0.17        29
weighted avg       0.18      0.17      0.17        29

c:\Users\surya prasad mallik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\surya prasad mallik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\surya prasad mallik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\surya prasad mallik\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


# Model 3: Random Forest Classifier

In [15]:

rf_model = RandomForestClassifier()

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

In [16]:

print("Random Forest Metrics")

print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf, average='weighted'))
print("Recall:", recall_score(y_test, y_pred_rf, average='weighted'))
print("F1 Score:", f1_score(y_test, y_pred_rf, average='weighted'))

print("\nClassification Report")
print(classification_report(y_test, y_pred_rf))

Random Forest Metrics
Accuracy: 0.2413793103448276
Precision: 0.44290192566054637
Recall: 0.2413793103448276
F1 Score: 0.27893715479922376

Classification Report
              precision    recall  f1-score   support

           0       0.09      0.33      0.14         3
           1       0.14      0.25      0.18         4
           2       0.67      0.33      0.44         6
           3       0.00      0.00      0.00         3
           4       0.00      0.00      0.00         3
           5       0.50      0.25      0.33         4
           6       1.00      0.50      0.67         2
           7       1.00      0.25      0.40         4

    accuracy                           0.24        29
   macro avg       0.43      0.24      0.27        29
weighted avg       0.44      0.24      0.28        29